'use client';

import { useState } from 'react';
import { ChevronDownIcon } from '@heroicons/react/24/outline';

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: "Will investors accept documents generated by Legmint?",
    answer: "Yes, absolutely. Our SAFE agreements follow the Y Combinator standard used by thousands of funded startups. 500+ VC-backed companies have raised €2B+ using Legmint docs. Top-tier VCs (a16z, Sequoia, Accel) care about the content and legal accuracy, not who drafted it. All our templates are reviewed by Tier 1 law firms quarterly."
  },
  {
    question: "What if I mess up the questionnaire?",
    answer: "Our smart questionnaire adapts to your answers and flags potential issues in real-time. If something doesn't make sense (like a co-founder getting 0% equity), we'll warn you. Plus, you can preview the document before downloading. If you need extra confidence, you can connect with our verified startup lawyers for review at 70% less than traditional firm rates."
  },
  {
    question: "Do I need a founders agreement for my startup?",
    answer: "Yes, absolutely. A founders agreement protects all co-founders by clearly defining equity split, vesting schedules, roles, and what happens if someone leaves. It prevents costly disputes later—23% of startup failures stem from co-founder conflicts. Get yours done in 15 minutes with Legmint instead of paying €3,000+ to a lawyer."
  },
  {
    question: "What is a SAFE agreement and when do I need it?",
    answer: "A SAFE (Simple Agreement for Future Equity) is the standard instrument for pre-seed and seed fundraising, created by Y Combinator. It's simpler and faster than convertible notes, with no interest or maturity date. Use it when raising your first €50K-€2M from angels or early VCs. Legmint generates investor-ready SAFEs in minutes."
  },
  {
    question: "How much do startup lawyers typically cost?",
    answer: "Traditional startup law firms charge €250-500/hour with €15K-50K annual retainers. A single founders agreement costs €2-5K and takes 2-3 weeks. A SAFE agreement costs €3-5K. Legmint costs €99 one-time for essential docs or €49/month for unlimited access, completed in 15 minutes. Save 95% on legal costs."
  },
  {
    question: "Can I use Legmint docs for Series A+ fundraising?",
    answer: "For pre-seed and seed (up to €2M), yes—our templates cover everything you need. For Series A+, we recommend working with our partner law firms for custom term sheets and shareholder agreements, as these deals involve complex preferences and board structures. However, you can still use Legmint for everything else (employment contracts, NDAs, IP assignments, SaaS agreements) to save 80% on legal costs."
  },
  {
    question: "Are Legmint templates legally valid in my country?",
    answer: "Yes. We support 6 jurisdictions: UK, US (Delaware), Germany, France, Czech Republic, and Global English. All templates are drafted and reviewed by local startup lawyers specializing in venture law. Each document is jurisdiction-specific and compliant with local corporate law, employment law, and data protection regulations (GDPR, UK GDPR)."
  },
  {
    question: "What's the difference between Legmint and DIY legal templates?",
    answer: "DIY templates from Google are generic, often outdated (pre-2020), and risky—no guidance on what to fill in or when clauses don't apply. Legmint provides: (1) Lawyer-reviewed templates updated quarterly, (2) Smart questionnaires that guide you step-by-step, (3) Jurisdiction-specific versions, (4) Real-time validation, (5) Direct lawyer access for review. Better than DIY, 95% cheaper than lawyers."
  },
  {
    question: "Do I still need a lawyer if I use Legmint?",
    answer: "For most standard documents (founders agreement, SAFE, NDA, employment contracts, IP assignments), no—our templates are lawyer-reviewed and cover 90% of early-stage startup needs. For complex situations (multiple investor classes, M&A, disputes, non-standard deal terms), we recommend review by our network of verified startup lawyers. They charge 15-25% less than traditional firms and integrate directly with Legmint."
  },
  {
    question: "What legal documents do I need for pre-seed fundraising?",
    answer: "Essential pre-seed documents: (1) SAFE or convertible note for investors, (2) Founders agreement with vesting schedules, (3) Board resolution approving fundraise, (4) IP assignment agreements, (5) Cap table. Recommended for investor data room: Articles of incorporation, employment contracts, privacy policy. Legmint has all templates ready to generate in 15 minutes."
  }
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="mb-12">
      <div className="text-center mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-3">
          Frequently Asked Questions
        </h2>
        <p className="text-gray-600 max-w-2xl mx-auto">
          Everything startup founders ask about legal documents, lawyers, and costs
        </p>
      </div>

      <div className="max-w-3xl mx-auto space-y-3">
        {faqs.map((faq, index) => (
          <div
            key={index}
            className="card bg-white border border-gray-200 overflow-hidden"
          >
            <button
              onClick={() => toggleFAQ(index)}
              className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-gray-50 transition-colors duration-200"
            >
              <h3 className="text-lg font-semibold text-gray-900 pr-4">
                {faq.question}
              </h3>
              <ChevronDownIcon
                className={`w-5 h-5 text-gray-500 flex-shrink-0 transition-transform duration-200 ${
                  openIndex === index ? 'transform rotate-180' : ''
                }`}
              />
            </button>
            {openIndex === index && (
              <div className="px-6 pb-4 text-gray-700 leading-relaxed border-t border-gray-100 pt-4">
                {faq.answer}
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="text-center mt-8">
        <p className="text-sm text-gray-500">
          Still have questions?{' '}
          <a href="/help" className="text-primary-600 hover:text-primary-700 font-medium">
            Contact our team
          </a>
        </p>
      </div>
    </section>
  );
}

